samples:
    Thalassiosira_weissflogii:
        ksizes:
            - 27
            - 35
            - 43
        storage: SparseppSetStorage
        type: transcriptome
        resources:
            mem: 16
            hours: 4
        intervals:
            fine: 10000
            medium: 1000000
            coarse: 5000000
        accession: SRR1300476
    Asterionellopsis_glacialis:
        ksizes:
            - 27
            - 35
            - 43
        storage: SparseppSetStorage
        type: transcriptome
        resources:
            mem: 16
            hours: 4
        intervals:
            fine: 10000
            medium: 1000000
            coarse: 5000000
        accession: SRR1300451
    Saccharomyces_cerevisiae:
        ksizes:
            - 27
            - 35
            - 43
        storage: SparseppSetStorage
        type: transcriptome
        resources:
            mem: 16
            hours: 4
        intervals:
            fine: 10000
            medium: 1000000
            coarse: 5000000
        accession: SRR453567
    Danio_rerio:
        ksizes:
            - 43
            - 55
            - 67
        storage:  SparseppSetStorage
        type: genome
        resources:
            mem: 128
            hours: 24
        intervals:
            fine: 50000
            medium: 1000000
            coarse: 10000000
        accession: SRR7081557

hu_metagenome:
    resources:
        mem: 8
        hours: 4
    type: metagenome
    storage: SparseppSetStorage
    ksizes:
        - 31

result_format: 'outputs/{sample}/{analysis}/{ksize}/'

analyses:

    boink_cdbg_stats:
        result: 'boink.cdbg.components.csv'
    boink_normalized_cdbg_stats:
        result: 'boink.cdbg.components.csv'
    bcalm:
        result: 'unitigs.fa'
